### ISSUE TITLE
How can we change the HDD logged ?

### ISSUE THREAD

**Issue by gtrhayrug** [mathoudebine/turing-smart-screen-python#101]
Hi,

I want to change the drive checked for size/free space.
Where is it ? 

By default, seems to be /
If i want to check the size of /dev/sdaX per example, where can i make the modification ?

Thanks 👍

**Comment by mathoudebine** [comment]
Hi @gtrhayrug 
It is not possible for now to change the HDD being monitored from the configuration file, but it can be done manually:

Note that you cannot monitor a disk because used/free space are statistics that apply for disk partitions only. To monitor a partition, it has to be mounted otherwise it is not possible to get stats.

By default this program monitor "/" aka the mounted partition of the disk containing your filesystem.
If you want to monitor another partition (e.g. if you have "/home" in a different partition or on another disk) you can modify `library/stats.py` l.503 to indicate the mountpoint of the partition instead of "/":
```python
disk_usage = psutil.disk_usage("/home")
```
More information here: https://psutil.readthedocs.io/en/latest/index.html?highlight=disk%20usage#psutil.disk_usage

**Comment by gtrhayrug** [comment]
Thanks for your reply but i've tried to take a look on the last github, especially on stats.py.
In the class Disk, even in line 503, i don't find the mountpoint as / or an equivalent line...

Maybe i missed something ?

**Comment by mathoudebine** [comment]
Oh yes sorry for this, the code has been reorganized for the 2.2.0 release.
Disk monitoring has been moved here:
https://github.com/mathoudebine/turing-smart-screen-python/blob/main/library/sensors/sensors_python.py#L238

**Comment by gtrhayrug** [comment]
Thanks, keeping / finally.
Can't access to pve disk images ...
