### ISSUE TITLE
Vanguard block inpoutx64.sys

### ISSUE THREAD

**Issue by kiam001** [mathoudebine/turing-smart-screen-python#165]
![image](https://user-images.githubusercontent.com/10757700/219655589-9d4c37e5-102b-4661-a230-6e5120a3f9d7.png)

**Comment by mathoudebine** [comment]
Hi @kiam001
The file inpoutx64.sys is an old driver that is vulnerable and can be used insecurely, that's why it is blacklisted by Vanguard.
It can be installed on your computer by some software like Asus OCT, Gigabyte, OpenRGB, Logitech GHub... it is used for fan speeds or RGB leds on some hardware.
Once it has been installed on your system, LibreHardwareMonitor library will try to use it to access some hardware sensors, and it will get blocked by Vanguard.

I do not recommend to delete the file `inpoutx64.sys` because it may still be used by some software, you could have blue screen.
What you can try is deleting these 2 registry keys (please make a backup first):
- Computer\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\inpoutx64
- Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\inpoutx64

Then reboot the computer and try again.

**Comment by kiam001** [comment]
Thx i will try whan i Home. 

If the issued fixed with thats i Close the Ticket

**Comment by kiam001** [comment]
Whan it works, after Test add this way To redme / Docs

**Comment by mathoudebine** [comment]
Thanks, I've added this to the Troubleshooting page on the wiki: https://github.com/mathoudebine/turing-smart-screen-python/wiki/Troubleshooting#windows-riot-vanguard-blocks-the-program-inpoutx64sys
