### ISSUE TITLE
Python 3.12: Can't get python dependencies installed

### ISSUE THREAD

**Issue by Paradoxum** [mathoudebine/turing-smart-screen-python#354]
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/6451395/8617c53d-ca49-42e6-9158-9bc82eb2b31f)

**To Reproduce**  
run > python.exe -m pip install -r requirements.txt

**Expected behavior**  
installs fine

**Environment:**  
 - SXuanFang 3.5
 - latest
 - w11 22h2 22621.2361
 - python-3.12.0-amd64.exe

**Comment by Paradoxum** [comment]
Forgot to add bottom of shell;' 
![image](https://github.com/mathoudebine/turing-smart-screen-python/assets/6451395/03b0178c-8b3d-41f9-a5bf-4d8cea78c316)

**Comment by mathoudebine** [comment]
Hello, Python 3.12 is not compatible with this project for now.
This is because we use some libraries that have not been updated yet.

For now you need to keep Python 3.11 until this issue is fixed. Don't worry, Python 3.11 is still actively supported until 2027-10!
You can uninstall Python 3.12 and install Python 3.11 from here: [python.org/downloads/release/python-3116](https://www.python.org/downloads/release/python-3116/) downloads are at the end of the page

**Comment by mathoudebine** [comment]
Hello again, Python 3.12 support is now enabled on the main branch (and in the future release)
Of course you can keep Python 3.11 that will work fine as well
