### ISSUE TITLE
GPU memory reads 0

### ISSUE THREAD

**Issue by Cyruz143** [mathoudebine/turing-smart-screen-python#43]
**Describe the bug**  
GPU memory (VRAM) stats report 0 on Cyberpunk and 3.5inchTheme2 themes. Terminal (which uses a bar) seems to report use fine.

**To Reproduce**  
1. Cycle between themes
2. Review GPU memory being 0m on Cyberpunk and 3.5inch

**Expected behavior**  
A value (other than 0) should appear

**Screenshots / photos of the Turing screen**  
https://cdn.discordapp.com/attachments/324263377272700928/1019190794697064448/IMG_20220913_111946.jpg

**Environment:**  
 - Release 2.0.2
 - Windows 10
 - 3.10.6
 - Nvidia GPU

**Comment by mathoudebine** [comment]
Hi, thanks for raising this issue.
There was an issue in the GPU VRAM stats that were displayed in bytes instead of Mbytes for NVidia GPU.
This issue should now be fixed in the latest commit.
Please note: in this commit, unavailable GPU metrics are now hidden (instead of displaying empty graphs / zero values).
