### ISSUE TITLE
Unable to detect COM port on Fedora Linux

### ISSUE THREAD

**Issue by AwekM** [mathoudebine/turing-smart-screen-python#50]
**Describe the bug**  
Error when executing main.py

**To Reproduce**  
1. Download the latest release (2.0.3)
2. Run python3 -m pip install -r requirements.txt
3. No changes made on config.yaml since I'm using revision A with "AUTO" COM port 
4. Run python3 main.py

**Screenshots/ photos of the Turing screen**  
![1](https://user-images.githubusercontent.com/113235053/191003710-ee58de68-3f39-4975-a17a-293029cb5386.png)
![2](https://user-images.githubusercontent.com/113235053/191004540-4388562c-55d4-4031-80c2-1804108dcc80.png)

But If I set  "/dev/ttyACM0" as the COM port, this is the error
![3](https://user-images.githubusercontent.com/113235053/191005304-e63ad891-2f31-4730-8eda-2d436fe3848d.png)

**Environment:**  
 - Release or branch of this project [Release 2.0.3]
 - OS with version [Fedora Linux 36]
 - Python version [Python 3.10.6]
 - Hardware [Ryzen 5 3600, GTX 1060 GB]

**Additional context**  
The error doesn't occur if I am using Gerph's fork (https://github.com/gerph/turing-smart-screen-python)
![4](https://user-images.githubusercontent.com/113235053/191006124-3ae66ebc-c7c0-45b8-99c8-2e9735244017.png)

**Comment by mathoudebine** [comment]
Hello!
Your issue here is linked to these 2 things:
* your user does not have permanent access to TTY devices, that's why you need to do a `chmod 666`
* this program reset the LCD when launched, and the reset make the LCD disconnect then reconnect. Because of this, the TTY is deleted then recreated (sometimes with another name e.g. ttyACM0 -> ttyACM1 as you can see in your logs) and the rights you previously assigned with chmod are lost.

To fis this, you have 2 solutions:
- either make your user access to all TTY permanently without chmod, by adding it to the group `dialout`, on Ubuntu the command is `sudo usermod -a -G dialout $USER`, should be similar on Fedora
- or remove the LCD reset, by commenting/deleting this line:
https://github.com/mathoudebine/turing-smart-screen-python/blob/main/library/display.py#L54

Let me know if it helps!

**Comment by AwekM** [comment]
Hi thank you for the solutions. Both solutions worked great. Thank you again for creating this program!

**Comment by lheinke** [comment]
@mathoudebine I had the same issue and had to search through the issues marked as closed. Maybe the steps to solve this problem could be added to the wiki?

**Comment by mathoudebine** [comment]
Done! It is now in a new Troubleshooting page on the wiki

**Comment by guglovich** [comment]
This information helped me to connect it. However, the image is not displayed. There are no errors.

**Comment by acaltas** [comment]
i have similar troubles to get this stuff running on my Bazzite Installation.
i have to use Distrobox on the Bazzite installation to use all the python stuff but i can not access or set the /dev/ttyACM0 as read.

what is the exact command line to commenting/deleting this line so that its not reloading the ttyACM0 ?
