### ISSUE TITLE
Error with requirement in windows

### ISSUE THREAD

**Issue by DroidBV8** [mathoudebine/turing-smart-screen-python#527]
Hello, I have this error on Windows 11 and last python version when I want to Install Python dependencies

`python.exe -m pip install -r requirements.txt`

Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
Ignoring GPUtil: markers 'python_version < "3.12"' don't match your environment
Collecting GPUtil@ git+https://github.com/mathoudebine/gputil.git@1.4.0-py3.12 (from -r requirements.txt (line 19))
  Cloning https://github.com/mathoudebine/gputil.git (to revision 1.4.0-py3.12) to c:\users\ultimatom\appdata\local\temp\pip-install-4i5m2wtz\gputil_c4c0ba583c7442f1b4881a2691118303
  ERROR: Error [WinError 2] Le fichier spécifié est introuvable while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by mathoudebine** [comment]
Hi, thanks for raising this issue.
It appears the documentation is not up-to-date for Python 3.12+: you need to install Git on your computer to be able to install this GPUtil fork https://github.com/mathoudebine/gputil that I'm maintaining, because the author has stopped its development.
Please download Git for Windows from here https://git-scm.com/ and install it with default options
